# Generated by Django 6.0.1 on 2026-03-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notes_files/'),
        ),
    ]
