# Generated by Django 6.0.1 on 2026-03-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='_content',
            field=models.BinaryField(db_column='content', default=b''),
            preserve_default=False,
        ),
    ]
