# Generated by Django 5.2.6 on 2026-03-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_note_content_note__content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='_content',
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
