# Generated by Django 5.2.6 on 2026-03-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note__content_note_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='_content',
            field=models.BinaryField(db_column='content', default=b''),
        ),
    ]
